
name: PUSH Staging Workflow

on:
  push:
    branches:
      - staging

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_STAGING_PASSWORD }}
          MYSQL_DATABASE: authmicroservice
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_STAGING_PASSWORD }}
          DB_DATABASE: authmicroservice
        run: |
          php artisan migrate --seed
          php artisan test
  deploy-staging:
    name: Deploy Project to STAGING Server
    runs-on: ubuntu-latest
    needs: [app-tests]
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        env:
            DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOT_ENV
          script: |
            sudo mkdir -p /tmp/staging
            cd /tmp/staging && sudo git clone git@github.com:username/repo.git
            cd /tmp/staging/repo
            sudo git checkout staging
            sudo chmod -R 777 /tmp/staging/repo
            sudo touch .env
            echo "$DOT_ENV" | sudo tee /tmp/staging/repo/.env
            composer install
            sudo php artisan migrate:refresh --seed && sudo php artisan test
            sudo php artisan scribe:generate && php artisan config:clear
            sudo rm -r /tests/www/repo-old
            sudo mv /tests/www/repo /tests/www/repo-old
            sudo mkdir -p /tests/www/repo
            sudo cp -r /tmp/staging/repo/* /tests/www/repo
            sudo rm -r /tmp/staging/repo
            echo "$DOT_ENV" | sudo tee /tests/www/repo/.env
            sudo chmod -R 777 /tests/www/repo/storage
            sudo supervisorctl reread && sudo supervisorctl update


