
name: PUSH Production Workflow

on:
  push:
    branches:
      - production

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4.27
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_PRODUCTION_PASSWORD }}
          MARIADB_DATABASE: ${{ secrets.DB_PRODUCTION_NAME }}
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install NPM
        run: npm install && npm run build
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PRODUCTION_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_PRODUCTION_NAME }}
        run: |
          php artisan migrate
          php artisan test
  deploy-production:
    name: Deploy Project to PRODUCTION Server
    runs-on: ubuntu-latest
    needs: [app-tests]
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        env:
            DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
            PAT: ${{ secrets.PAT }}
            $DEPLOY_PATH_PRODUCTION: ${{ secrets.DEPLOY_PATH_PRODUCTION }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOT_ENV, PAT, DEPLOY_PATH_PRODUCTION
          script: |
            sudo mkdir -p /tmp/production/repo
            sudo chmod -R 777 /tmp/production/repo
            cd /tmp/production && git clone https://$PAT@github.com/monitecture/repo.git
            cd /tmp/production/repo
            sudo git checkout production
            sudo touch .env
            echo "$DOT_ENV" | sudo tee /tmp/production/repo/.env
            composer install
            sudo php artisan migrate --force
            sudo php artisan config:clear
            sudo rm -r $DEPLOY_PATH_PRODUCTION/repo-old
            sudo mv $DEPLOY_PATH_PRODUCTION/repo $DEPLOY_PATH_PRODUCTION/repo-old
            sudo mkdir -p $DEPLOY_PATH_PRODUCTION/repo
            sudo cp -r /tmp/production/repo/* $DEPLOY_PATH_PRODUCTION/repo
            sudo rm -r /tmp/production/repo
            echo "$DOT_ENV" | sudo tee $DEPLOY_PATH_PRODUCTION/repo/.env
            sudo chmod -R 0755 $DEPLOY_PATH_PRODUCTION/repo
            sudo chmod -R ugo+rw $DEPLOY_PATH_PRODUCTION/repo/storage

