
name: PUSH Production Workflow

on:
  push:
    branches:
      - main

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PRODUCTION_PASSWORD }}
          MYSQL_DATABASE: authmicroservice
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PRODUCTION_PASSWORD }}
          DB_DATABASE: authmicroservice
        run: |
          php artisan migrate
          php artisan test
  deploy-production:
    name: Deploy Project to PRODUCTION Server
    runs-on: ubuntu-latest
    needs: [app-tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        env:
            DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOT_ENV
          script: |
            sudo mkdir -p /tmp/production
            cd /tmp/production && sudo git clone git@github.com:username/repo.git
            cd /tmp/production/repo
            sudo git checkout main
            sudo chmod -R 777 /tmp/production/repo
            sudo touch .env
            echo "$DOT_ENV" | sudo tee /tmp/production/repo/.env
            composer install
            sudo php artisan migrate --force
            sudo php artisan config:clear
            sudo rm -r /apps/www/repo-old
            sudo mv /apps/www/repo /apps/www/repo-old
            sudo mkdir -p /apps/www/repo
            sudo cp -r /tmp/production/repo/* /apps/www/repo
            sudo rm -r /tmp/production/repo
            echo "$DOT_ENV" | sudo tee /apps/www/repo/.env
            sudo chmod -R 777 /apps/www/repo/storage
            sudo supervisorctl reread && sudo supervisorctl update

